### ISSUE TITLE
Full stack harjoitustyön katselmointi

### ISSUE THREAD

**Issue by outisa** [Melimet/Birdnest-Solution#1]
Hei @Melimet

Katselmoin Full stack harjoitustyösi. Repositoriosta saa hyvän ensivaikutelman, sillä READMEsta selviää mistä on kyse ja repoon on lisätty lisenssi.

**Kommentteja**
- Erittäin hieno juttu, että olet opetellut uusia teknologioita projektin aikana (AWS).
- Koodisi on siistiä ja selkeästi organisoitua.
- Henkilökohtaisesti siivoaisin ylimääräiset dataa loggaavat console.logit pois. Ne ovat korvaamattomia kehitysvaiheessa, mutta  tuotantokoodissa datan loggausta konsoliin olisi ehkä hyvä välttää.
- Hienoa, että olet tehnyt  harjoitustyöhösi myös toimivan CI/CD -putken, testejä sekä skriptejä helpottamaan käyttöä.
- Oli todella helppo kloonata projekti ja käynnistää sovellus ohjeen avulla omalla koneella.

Hienoa työtä!

**Comment by Melimet** [comment]
Kiitos palautteesta!
